spring:
  datasource:
   url: jdbc:h2:tcp://localhost/~/test
   driver-class-name: org.h2.Driver
   username: sa
   password: 1004

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  
server:
  port: 9090